---
title: "Publications"
output: html_document
---

<link rel="stylesheet" href="styles.css" type="text/css">

<!-- ## Crowther Lab, ETH Zürich -->
A full list of publications is available on [Google Scholar](https://scholar.google.com/citations?user=0Pl8Q1EAAAAJ&hl=en).

**van den Hoogen, J.**, S. Geisen, D. Routh, H. Ferris, W. Traunspurger, D. Wardle, R. de Goede, B. Adams, W. Ahmad, W. S. Andriuzzi, R. D. Bardgett, M. Bonkowski, R. Campos-Herrera, J. E. Cares, T. Caruso, L. de B. Caixeta, X. Chen, S. dos S. da R. Costa, R. Creamer, J. M. da C. Castro, M. Dam, D. Djigal, M. Escuer, B. Griffiths, C. Gutiérrez, K. Hohberg, D. Kalinkina, P. Kardol, A. Kergunteuil, G. Korthals, V. Krashevska, A. Kudrin, Q. Li, W. Liang, M. Magilton, M. Marais, J. A. R. Martín, E. Matveeva, E. H. Mayad, C. Mulder, P. Mullin, R. Neilson, D. Nguyen, U. N. Nielsen, H. Okada, J. E. P. Rius, K. Pan, V. Peneva, L. Pellissier, J. C. P. da Silva, C. Pitteloud, T. O. Powers, K. Powers, C. Quist, S. Rasmann, S. S. Moreno, S. Scheu, H. Setälä, A. Sushchuk, A. Tiunov, J. Trap, W. van der Putten, M. Vestergård, C. Villenave, L. Waeyenberge, D. H.Wall, R. Wilschut, D. Wright, J. Yang, T. W. Crowther (2019). Soil nematode abundance and functional group composition at a global scale. *Nature*, doi: [10.1038/s41586-019-1418-6](https://www.nature.com/articles/s41586-019-1418-6)

Crowther, T.W., **J. van den Hoogen**, J. Wan, M. A. Mayes, A. D. Keiser, L. Mo, C. Averill, D. S. Maynard (2019). The global soil community and its influence on biogeochemistry. *Science*, doi: [10.1126/science.aav0550](https://science.sciencemag.org/content/365/6455/eaav0550)

H.R.P. Phillips, C.A. Guerra, M.L.C. Bartz, M.J.I. Briones, G. Brown, T.W. Crowther, Olga Ferlian, K.B. Gongalsky, **J. van den Hoogen**, et al., E.K. Cameron and N. Eisenhauer (2019). Global distribution of earthworm diversity. *Science*, doi: [10.1126/science.aax4851](https://doi.org/10.1126/science.aax4851)

G.R. Smith, T.W. Crowther, N. Eisenhauer and **J. van den Hoogen** (2019). Building a global database of soil microbial biomass and function: a call for collaboration. *Soil Organisms*, doi: [10.25674/so91iss3pp140](http://soil-organisms.org/index.php/SO/article/view/112)

**van den Hoogen, J.**, S. Geisen, D.H. Wall, D.A. Wardle, W. Traunspurger, R.G.M. de Goede, B.J. Adams, W. Ahmad, H. Ferris, R. D. Bardgett, M.Bonkowski, R. Campos-Herrera, J.E. Cares, Tancredi Caruso, L. de Brito Caixeta, X. Chen, S.R. Costa, R. Creamer, J.M. da Cunha e Castro, M. Dam, D. Djigal, M. Escuer, B.S. Griffiths, C. Gutiérrez, K. Hohberg, D. Kalinkina, P. Kardol, A. Kergunteuil, G. Korthals, V. Krashevska, A.A. Kudrin, Q. Li, W. Liang, M. Magilton, M. Marais, J.A. Rodríguez Martín, E. Matveeva, H. Mayad, E. Mzough, C. Mulder, P. Mullin, R. Neilson, T. A. Duong Nguyen, U.N. Nielsen, H. Okada, J.E. Palomares Rius, K. Pan, V. Peneva, L. Pellissier, J.C. Pereira da Silva, C. Pitteloud, T.O. Powers, K. Powers, C.W. Quist, S. Rasmann, S.S. Moreno, S Scheu, H. Setälä, A. Sushchuk, A.V. Tiunov, J. Trap, M. Vestergård, C. Villenave, L. Waeyenberge, R.A. Wilschut, D.G. Wright, A.M. Keith, J. Yang, O. Schmidt, R. Bouharroud, Z. Ferji, W.H. van der Putten , D. Routh & T W. Crowther (2020). A global database of soil nematode abundance and functional group composition. *Scientific Data*, doi: [10.1038/s41597-020-0437-3](https://www.nature.com/articles/s41597-020-0437-3)

Bastin, J. F., E. Clark, T. Elliott, S. Hart, **J. van den Hoogen**, I. Hordijk, H. Ma, S. Majumder, G. Manoli, J. Maschler, L. Mo, D. Routh, K. Yu, C. M. Zohner and T. W. Crowther (2019). Understanding climate change from a global analysis of city analogues. *PLOS One*, doi: [10.1371/journal.pone.0217592](https://journals.plos.org/PLOSone/article?id=10.1371/journal.pone.0217592)

**van den Hoogen, J.**. and F. Govers (2018). GPCR-bigrams: Enigmatic signaling components in oomycetes. *PLOS Pathogens*, doi: [10.1371/journal.ppat.1007064](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1007064)

**van den Hoogen, J.**, N. Verbeek-de Kruif and F. Govers (2018). The G-protein gamma subunit of *Phytophthora infestans* is involved in sporangial development. *Fungal Genetics and Biology*, doi: [10.1016/j.fgb.2018.04.012](https://www.sciencedirect.com/science/article/pii/S1087184518300719)

**van den Hoogen, D. J.**, H. J. G. Meijer, M. F. Seidl and F. Govers (2018). The ancient link between G-protein coupled receptors and C-terminal phospholipid kinase domains. *mBio*, doi: [10.1128/mBio.02119-17](https://mbio.asm.org/content/9/1/e02119-17)

R. van Velzen, R. Holmer, F. Bu, L Rutten, A. van Zeijl, W. Liu, L. Santuari, Q. Cao, T. Sharma, D. Shen, Y. Roswanjaya, T. A. K. Wardhani, M. S. Kalhor, J. Jansen, **J. van den Hoogen**, B. Güngör, M. Hartog, Jan Hontelez, J. Verver, W-C. Yang, E. Schijlen, R. Repin, M. Schilthuizen, M. E. Schranz, R. Heidstra, K. Miyata, E. Fedorova, W. Kohlen, T. Bisseling, S. Smit, and R. Geurts (2018). Comparative genomics of the nonlegume *Parasponia* reveals insights into evolution of nitrogen-fixing rhizobium symbioses. *Proceedings of the National Academy of Sciences*, doi: [10.1073/pnas.1721395115](https://www.pnas.org/content/115/20/E4700)

M. Thines, R. Sharma, S. Y. A. Rodenburg, A. Gogleva, H. S. Judelson, X. Xia, **J. van den Hoogen**, M. Kitner, J. Klein, M. Neilen, D. de Ridder, M. F. Seidl, G. van den Ackerveken, F. Govers, S. Schornack, D. J. Studholme (2020). The genome of *Peronospora belbahrii* reveals high heterozygosity, a low number of canonical effectors and CT-rich promoters. *Molecular Plant-Microbe Interactions*, doi: [10.1094/MPMI-07-19-0211-R](https://apsjournals.apsnet.org/doi/abs/10.1094/MPMI-07-19-0211-R)

R. Sharma, X. Xia, L. M. Cano, E. Evangelisti, E. Kemen, H. Judelson, S. Oome, C. Sambles, **D. J. van den Hoogen**, M. Kitner, J. Klein, H. J. G. Meijer, O. Spring, J. Win, R. Zipper, H. B. Bode, F. Govers, S. Kamoun, S. Schornack, D. J. Studholme, G. Van den Ackerveken, and M. Thines (2015). Genome analyses of the sunflower pathogen *Plasmopara halstedii* provide insights into effector evolution in downy mildews and *Phytophthora*. *BMC Genomics*, doi: [10.1186/s12864-015-1904-7](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-1904-7)

### Preprints

**van den Hoogen, J.** and F. Govers (2018). Attempts to implement CRISPR/Cas9 for genome editing in the oomycete *Phytophthora infestans*. *bioRxiv*, doi: [10.1101/274829](https://www.biorxiv.org/content/10.1101/274829v2)
